### ISSUE TITLE
bad argument #1 to 'srtfind' (string expected, got nil)

### ISSUE THREAD

**Issue by F0R3V3RGT** [abc123rp/abc_blipsems#1]
Hi ABC, iam having a problem with your script, when I try to do /iden (/identifier) ​​it gives me error and also when I do the other commands /bon (/blipON) and /boff (/blipOFF).

The error that gives me is this https://prnt.sc/u5ta7q

My version of essentialmode is 6.3.0.

If you could help me, I would appreciate it a lot.

**Comment by abc123rp** [comment]
Hey F0R3V3RGT i hope you are fine this morning, you need to wire some arguments when writing command like /identifier 101 | [Character Name]

**Comment by abc123rp** [comment]
Hey try to use it without changing any code and reply if the error consists

**Comment by abc123rp** [comment]
Solved on new commit
